import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { watch } from 'node:fs';
import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Set OBSIDIAN_PLUGIN_DIR (e.g. in .env) to copy the build into a vault after every rebuild.
const pluginDir = process.env.OBSIDIAN_PLUGIN_DIR;

const copyToVault = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd(async (result) => {
			if (!pluginDir || result.errors.length > 0) return;
			await mkdir(pluginDir, { recursive: true });
			for (const file of ['main.js', 'manifest.json', 'styles.css']) {
				await copyFile(file, join(pluginDir, file));
			}
			// Tells the hot-reload plugin to reload this plugin when it changes.
			await writeFile(join(pluginDir, '.hotreload'), '');
			console.log(`Copied build to ${pluginDir}`);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [copyToVault],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	// esbuild only watches the TS graph; copy CSS/manifest edits to the vault too.
	if (pluginDir) {
		for (const file of ['styles.css', 'manifest.json']) {
			watch(file, () => void copyFile(file, join(pluginDir, file)).catch(console.error));
		}
	}
}
